[PW-5915] Add address regex for special characters for version 8
Adyen/adyen-magento2 pull request #1268
Opened 2021-12-02 10:03 UTC by AlexandrosMor

**Description**

Polish addresses are not parsed properly because of the special characters.
Improving the regex which extract the house number from the street line if needed fixes that issue
**Tested scenarios**

- Address without special characters
- Address with special characters

2021-12-02 15:27 UTC, peterojo approved these changes

2021-12-02 16:13 UTC, Morerice submitted a review, later dismissed

2021-12-03 10:21 UTC, michaelpaul requested changes

2021-12-03 10:21 UTC, michaelpaul commented on Helper/Address.php
> +    const STREET_FIRST_REGEX = "/(?<streetName>[A-Za-zÀ-ÖØ-öø-ÿ0-9.'\- ]+)\s+(?<houseNumber>\d{1,10}((\s)?\w{1,3})?)$/";
How about if we consider these strings as unicode and match them as alphanumeric?  
```suggestion
    const STREET_FIRST_REGEX = "/(?<streetName>[[:alnum:].'\- ]+)\s+(?<houseNumber>\d{1,10}((\s)?\w{1,3})?)$/u";
```
We can add unit tests for these cases at `Test/Unit/Helper/AddressTest.php`.

2021-12-03 14:48 UTC, michaelpaul approved these changes

2021-12-03 15:29 UTC, Morerice approved these changes

2021-12-03 15:29 UTC, merged