[PW-5925] State data clean up
Adyen/adyen-magento2 pull request #1272
Opened 2021-12-02 15:20 UTC by acampos1916

**Description**

**Tested scenarios**

**Fixed issue**:

2021-12-03 15:45 UTC, michaelpaul requested changes

2021-12-03 15:45 UTC, michaelpaul commented on Observer/AdyenSalesOrderClearStateDataObserver.php
> +class AdyenClearStateDataObserver implements ObserverInterface
The filename does not match with the classname causing an autoload error that breaks the checkout. It needs to be renamed:

Observer/AdyenSalesOrderClearStateDataObserver.php -> Observer/AdyenClearStateDataObserver.php

2021-12-17 08:41 UTC, AlexandrosMor commented
Hey @acampos1916, Could you add some description for this code change ? :)

2021-12-17 09:13 UTC, AlexandrosMor approved these changes

2022-04-21 14:11 UTC, Morerice commented
Closing this PR because since https://github.com/Adyen/adyen-magento2/pull/1302 we are no longer storing the stateData in the database.

2022-04-21 14:11 UTC, closed without merging