Pw 1796
Adyen/adyen-magento2 pull request #1303
Opened 2021-12-30 14:53 UTC by tnaber

![image](https://user-images.githubusercontent.com/23633368/147762442-20047aa8-b9ba-437a-a43f-50e4ccee40bc.png)

**Description**
Fixes #542 

**Tested scenarios**
Adding wrong and correct SSN

**Fixed issue**:

2021-12-31 13:32 UTC, AlexandrosMor submitted a review, later dismissed

2022-01-05 10:09 UTC, michaelpaul requested changes
The `validate-ssn` validator expects the North American Social Security Number format  (e.g. 123-45-6789) which is different from Brazilian format (e.g. 123.123.123-12).

I tested this only switching currency to BRL. Maybe changing another configuration would work?  

I also tested Drop-In at https://www.mystoredemo.io/ and it does validation and formatting in Brazilian format. Maybe that's something Components can do as well.

2022-01-21 14:03 UTC, michaelpaul approved these changes

2022-01-24 12:57 UTC, acampos1916 approved these changes

2022-01-24 13:11 UTC, AlexandrosMor approved these changes

2022-01-24 14:10 UTC, merged