Helper/Webhook.php
Adyen/adyen-magento2 pull request #1397
Opened 2022-03-16 12:45 UTC by tnaber

**Description**
This PR addresses the issue from #1173.
When configuring statuses, a status can be assigned to multiple states. 
_E.g. the status 'Waiting for capture' can be assigned to both the 'pending_payment' and 'processing' state. When configuring "Order status: payment authorisation" it is possible to select statuses that lead to the 'processing' state, thus 'Waiting for capture' is shown in the dropdown. When this status is selected it is possible for the flow to enter the 'pending_payment' state. This should not be possible._

Further explanation of the problem and the corresponding code can be found in #1173. This PR proposes a solution in which the possible states are passed as a parameter when the `setState` function is called in the Webhook module. Before selecting a state to enter, the list of possible states will be filtered on this parameter. 
_E.g. this will prevent the 'pending_payment' state from the example to be removed._

When multiple states are possible to enter, and the passed status is also tied to all of these states. The first one will be selected. This means the unpredictability is not fully removed, however this should be clear to the user as the 'Waiting for capture' label will appear multiple times in the dropdown.

**Tested scenarios**
- [x] Tested for multiple states

**Fixed issue**: 
Fixes #1173

2022-03-16 15:39 UTC, acampos1916 requested changes

2022-03-16 15:39 UTC, acampos1916 commented on Helper/Webhook.php
> +        $possibleStates = ['new', 'processing'];
I would propose to move these states and the finalizeOrder ones to a constant multidimensional array in this class

2022-03-17 10:14 UTC, AlexandrosMor approved these changes

2022-03-28 07:06 UTC, acampos1916 approved these changes

2022-03-28 09:00 UTC, merged