[PW-6209] Update LPM recurring payments (v7)
Adyen/adyen-magento2 pull request #1401
Opened 2022-03-17 16:24 UTC by peterojo

**Description**
Implemented #1389 for v7

**Tested scenarios**
* Card payment
* Card payment (CardOnFile token created)
* Card payment (Subscription token created)
* Tokenized card payment (CardOnFile)
* SEPA payment
* SEPA payment (CardOnFile token created)
* SEPA payment (Subscription token created)

2022-03-21 13:18 UTC, tnaber approved these changes

2022-03-21 13:18 UTC, tnaber approved these changes

2022-03-21 14:59 UTC, Morerice requested changes

2022-03-21 14:59 UTC, Morerice commented on Logger/Handler/AdyenWarning.php
> +    protected $loggerType = AdyenLogger::ADYEN_WARNING;
I was referring to this in the previous message

2022-03-21 16:08 UTC, Morerice commented on Logger/Handler/AdyenWarning.php
> +    protected $loggerType = 300;
Can you re-use the constants here, like `AdyenLogger::WARNING` instead of hard-coding the int?

2022-03-22 09:50 UTC, Morerice approved these changes

2022-03-22 16:01 UTC, merged