[PW-5620] - Create download logs functionality
Adyen/adyen-magento2 pull request #1417
Opened 2022-03-28 13:26 UTC by candemiralp

**Description**

In order to easily obtain Adyen Logs, Download Logs functionality added under Advanced Settings tab in Configuration page.

**Tested scenarios**

**Fixed issue**:  PW-5620

2022-03-28 14:33 UTC, Morerice requested changes

2022-03-28 14:33 UTC, Morerice commented on Block/Adminhtml/System/Config/FieldSet/DownloadLogs.php
> +}
Could you add a new line at the end of the new files?

2022-03-28 14:33 UTC, Morerice commented on etc/adminhtml/system/adyen_logs.xml
> +        <comment>
I think this comment can be removed, cause it's already very clear from the button text

2022-03-29 11:42 UTC, AlexandrosMor approved these changes

2022-03-30 08:23 UTC, peterojo commented on Controller/Adminhtml/Logs/Download.php
> +}
```suggestion
}

```

2022-03-31 09:06 UTC, closed without merging