Added field validation for 'undefined' address
Adyen/adyen-magento2 pull request #1456
Opened 2022-04-12 15:24 UTC by tnaber

**Description**
When the layout is changed by the merchant it is possible for the payment methods to be loaded before the address is available. This causes a slice on an undefined object and causes and error.

**Fixed issue**:  
#1440

2022-04-12 15:24 UTC, tnaber commented on view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js
> +                    }
These are the actually added lines, the rest is reformatting

2022-04-13 07:51 UTC, tnaber commented
Hi @jonathanribas,
We're still looking into how to trigger this problem. Does you checkout page allow the payment methods to be loaded without an address being entered yet? E.g. having the payment methods and address detail fields on the same page?

2022-04-13 08:50 UTC, jonathanribas commented
Hi @tnaber, we actually use Adobe Commerce checkout with several steps (we don't have a One Step Checkout).

Payment methods are actually triggered by Adyen's module mixin: `vendor/adyen/module-payment/view/frontend/web/js/model/set-shipping-information-mixin.js`, as we have shipping cost estimation on our cart, we get Adyen Payment methods on cart.

If you want you can test it on https://uk.caudalie.com/

2022-04-19 14:04 UTC, tnaber commented
Hi @jonathanribas, 
I've found a new solution, it's not pretty so I'm leaving this as a draft for now in order to fully verify. If you are looking for a temporary solution feel free to check it out.

2022-04-19 14:28 UTC, jonathanribas commented
Hi @tnaber, thank you! At the moment we will keep our temporary workaround as we don't had other issues since implemented.
Looking forward the final solution from your side, maybe for next release 8.2.2?

2022-04-20 13:41 UTC, jonathanribas commented
Hi @tnaber, with those changes, do you still need to use `afterRender` on `cc-form.html`?

2022-04-20 13:46 UTC, tnaber commented
We might, as the field does not necessarily have to be available when the loadCheckoutComponent is ran. E.g. if we delete the afterRender and the loadCheckoutComponent function is ran for the last time before the field is available it will never retrigger the mount. 
However, I do agree that a single trigger would be neater and I'm still testing if we can do without one of both

2022-04-26 14:57 UTC, kbakkes commented
Hi, We are currently facing the same as described above.

2022-05-06 13:55 UTC, tnaber commented
Hi @kbakkes and @jonathanribas,

I have updated the fix and implemented a new flow. I am confident this should fix the issue.
If you would be able to test it that would be greatly appreciated!

Cheers,
Titus

2022-05-09 12:35 UTC, michaelpaul requested changes

2022-05-09 12:35 UTC, michaelpaul commented on view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
> +                                : {}
```suggestion
                            icon: paymentMethodsResponse.paymentMethodsExtraDetails.card.icon || {}
```

2022-05-09 14:03 UTC, michaelpaul approved these changes

2022-05-10 08:11 UTC, peterojo approved these changes

2022-05-11 07:53 UTC, merged