[PW-6726] Enable REFUND notifications to be processed
Adyen/adyen-magento2 pull request #1557
Opened 2022-06-02 15:29 UTC by RokPopov

**Description**
There was an issue with processing the REFUND notification when a credit memo (refund) was created. Magento sets the order state and status to cancelled. When we then attempt to process the webhook, there was no mapping for the order state in WEBHOOK_ORDER_STATE_MAPPING array. This solution adds the STATUS_CLOSED to the mentioned array and adds the `Notification::REFUND` case to the `handleUnchangedStates` function.

**Tested scenarios**
1. Place the order, process the AUTHORISATION notification related to it and ship it
2. Refund the order and process the REFUND notification
3. `Total_Refunded` column in `adyen_order_payment` updates with the correct value, as the REFUND notification is processed correctly

**Fixed issue**:  
Closes #1493

2022-06-02 16:59 UTC, candemiralp approved these changes

2022-06-03 07:00 UTC, AlexandrosMor approved these changes

2022-06-08 08:04 UTC, peterojo commented on Helper/Webhook.php
> +                $this->refundPayment($notification);
`refundPayment()` is already called in `handleOrderTransition()`. If `handleUnchangedStates()` is called it means that the webhook module has determined that the order is already in the desired state

2022-06-08 08:09 UTC, peterojo commented on Helper/Webhook.php
> +                $this->refundPayment($notification);
Probably adding closed state to the mapping should be enough to fix the issue

2022-06-08 08:10 UTC, peterojo requested changes
Could you test with removing the changes in `handleUnchangedStates`

2022-06-14 11:45 UTC, peterojo approved these changes

2022-06-16 11:35 UTC, merged