[PW-6911] - Resolve incompatibility with Magento 2.3.x
Adyen/adyen-magento2 pull request #1648
Opened 2022-08-04 13:37 UTC by candemiralp

**Description**

`getInitCustomerData()` function does not exist in Magento 2.3.x versions. Remove that additional check for existence of the customer information.

**Tested scenarios**

**Fixed issue**:   Closes #1615

2022-08-04 14:06 UTC, michaelpaul submitted a review, later dismissed

2022-08-04 15:42 UTC, RokPopov requested changes

2022-08-04 15:42 UTC, RokPopov commented on view/frontend/templates/checkout/success.phtml
> -
@candemiralp I think the convention is to have an empty line at the end of the file?

2022-08-05 12:02 UTC, RokPopov approved these changes

2022-08-05 13:45 UTC, michaelpaul approved these changes

2022-08-08 08:58 UTC, merged