[PW-6911-v7] - Resolve incompatibility with Magento 2.3.x
Adyen/adyen-magento2 pull request #1649
Opened 2022-08-04 13:59 UTC by candemiralp

**Description**

`getInitCustomerData()` function called on `success` page does not exist in Magento 2.3.x versions. Remove that additional check for existence of the customer information and reload cart directly.

**Tested scenarios**

**Fixed issue**:

2022-08-04 14:06 UTC, michaelpaul approved these changes

2022-08-04 15:44 UTC, RokPopov requested changes

2022-08-04 15:44 UTC, RokPopov commented on view/frontend/templates/checkout/success.phtml
> -
@candemiralp could you add a break line to the end of the file?

2022-08-05 12:02 UTC, RokPopov approved these changes

2022-08-05 13:45 UTC, michaelpaul approved these changes

2022-08-08 06:45 UTC, merged