[PW-7150]Add null for the moto merchant account
Adyen/adyen-magento2 pull request #1685
Opened 2022-08-30 14:26 UTC by AlexandrosMor

**Description**

In the ManagementHelper.php class the `$this->dataHelper->initializeAdyenClient` has wrong parameters which cause the management api config to throw an exception. The `initializeAdyenClient` has `$motoMerchantAccount` and it should be `null` when we do not use moto

**Tested scenarios**

**Fixed issue**:

2022-08-30 14:28 UTC, candemiralp submitted a review, later dismissed

2022-08-30 14:30 UTC, Morerice requested changes

2022-08-30 14:30 UTC, Morerice commented on Helper/ManagementHelper.php
> +        $client = $this->dataHelper->initializeAdyenClient($storeId, $apiKey,null, $environment === 'test');
```suggestion
        $client = $this->dataHelper->initializeAdyenClient($storeId, $apiKey, null, $environment === 'test');
```

2022-08-31 07:01 UTC, Morerice approved these changes

2022-08-31 07:17 UTC, peterojo approved these changes

2022-08-31 07:31 UTC, merged