[PW-7100] Add CardOnFile and UnshceduledCardOnFile to Vault Card
Adyen/adyen-magento2 pull request #1693
Opened 2022-08-31 14:13 UTC by RokPopov

**Description**
Currently when vault is selected for card payments, we are always sending Subscription (`Requests::buildCardRecurringData`). This should be changed to utilise the `recurring_card_token_type`, which is currently only used when `Adyen Tokenization` is selected in the admin panel.

With this PR, when `Vault` is selected in the admin panel, all `CardOnFile` recurring payments will be CVC-less.

**Tested scenarios**
- saved a token with the incorrect `tokenType` (`UnscheduledCardOnFile` and `Subscription`) for a logged-in user, proceeded to the checkout page and made sure that the stored payment methods are not showing payment methods list
- saved a token with the correct `tokenType` (`CardOnFile`) for a logged-in user, proceeded to the checkout page and made sure that the stored payment methods are showing payment methods list
- proceeded with placing the order, selecting the stored payment method with `CardOnFile` `tokenType` and made sure the payment was successful

2022-08-31 14:39 UTC, RokPopov commented on view/frontend/web/template/payment/payment-method-vault.html
> +-->
oeps!

2022-09-01 11:42 UTC, Morerice requested changes

2022-09-01 11:42 UTC, Morerice commented on Model/Ui/TokenUiComponentProvider.php
> +        $details['displayToken'] = $tokenType === Recurring::CARD_ON_FILE || !isset($tokenType);
```suggestion
        $details['displayToken'] = $tokenType === Recurring::CARD_ON_FILE || is_null($tokenType);
```

2022-09-01 11:42 UTC, Morerice commented on Plugin/CustomerFilterVaultTokens.php
> +    public function afterGetCustomerSessionTokens(CustomerTokenManagement $customerTokenManagement, array $customerSessionTokens)
```suggestion
    public function afterGetCustomerSessionTokens(CustomerTokenManagement $customerTokenManagement, array $customerSessionTokens): CustomerTokenManagement[]
```

2022-09-01 11:42 UTC, Morerice commented on etc/adminhtml/system/adyen_oneclick.xml
> +                Choose between CardOnFile (one-click CVC-less payments), UnscheduledCardOnFile (non-fixed schedule one-click CVC-less payments) or Subscription (fixed schedule payments)
```suggestion
                Choose between CardOnFile (one-click), UnscheduledCardOnFile (non-fixed schedule MIT payments) or Subscription (fixed schedule MIT payments)
```

2022-09-01 14:24 UTC, acampos1916 approved these changes

2022-09-02 11:56 UTC, Morerice approved these changes

2022-09-02 12:12 UTC, merged