[PW-4938] Add 3-digit padding helper method for shopperReference
Adyen/adyen-magento2 pull request #1766
Opened 2022-10-13 06:22 UTC by RokPopov

**Description**
Since checkout v66 Shopper reference should be 3 digits and above which means in cases that is less the api returns error. Add a method that pads all the shopper reference before adding it to any request.

**Tested scenarios**

2022-10-14 13:04 UTC, candemiralp commented on Model/AdyenInitiateTerminalApi.php
> +//                                    str_pad((string)$customerId, 3, '0', STR_PAD_LEFT);
Is this comment relevant?

2022-10-14 13:05 UTC, candemiralp commented on Model/Api/PaymentRequest.php
> -    private function getShopperReferencePadding($shopperReference)
Shall we keep this or delete?

2022-10-14 13:06 UTC, candemiralp commented on Helper/Data.php
> +    public function padShopperReference($customerId)
Let's use the variable name `shopperReference` instead of `customerId`.

2022-10-17 10:59 UTC, Morerice requested changes

2022-10-17 10:59 UTC, Morerice commented on Helper/Data.php
> +    public function padShopperReference($shopperReference): string
Can we also add the argument type?
```suggestion
    public function padShopperReference(string $shopperReference): string
```

2022-10-17 14:47 UTC, Morerice approved these changes

2022-10-18 11:55 UTC, AlexandrosMor approved these changes

2022-10-18 13:21 UTC, merged