[PW-7274] - Update street name and house number parsing regex
Adyen/adyen-magento2 pull request #1785
Opened 2022-10-24 07:22 UTC by candemiralp

**Description**

Regex script updated to parse more options.

- Sample Str. 23a-1
- Watermelon Weg 23-31, Test

2022-11-02 16:28 UTC, RokPopov approved these changes

2022-11-03 02:11 UTC, peterojo requested changes
Please add the new formats to the AddressTest

2022-11-03 07:04 UTC, candemiralp commented
> Please add the new formats to the AddressTest

Hey @peterojo thank you for your review. New scenarios wasn't added to the unit tests since `23a-1 Sample Str.` is not supported by the regex.

2022-11-03 07:15 UTC, peterojo approved these changes

2022-11-03 07:56 UTC, AlexandrosMor approved these changes

2022-11-03 08:15 UTC, merged