[PW-7387] - Fix credit memo creation condition for CA initiated refunds
Adyen/adyen-magento2 pull request #1839
Opened 2022-11-17 11:56 UTC by candemiralp

**Description**

The condition for checking the possibility of creation of the offline credit memo for CA initiated refunds fixed.

Creation of the credit memo for Adyen Customer Area initiated refund is only possible if the full amount is refunded **at once**. If a partial refund is initiated from Adyen Customer Area, merchant will be informed to create an offline credit memo.

**Tested scenarios**

- CA initiated refunds with manual/immediate capture
- Magento initiated refunds with manual/immediate capture

2022-11-22 15:56 UTC, RokPopov submitted a review, later dismissed

2022-11-23 08:11 UTC, Morerice requested changes

2022-11-23 08:11 UTC, Morerice commented on Helper/Order.php
> +                if (!is_null($payment->getCreditmemo())) {
```suggestion
                if (isset($payment->getCreditmemo())) {
```

2022-11-23 08:11 UTC, Morerice commented on Helper/Order.php
> +                    // add a comment why we are closing
Should we add a comment here or remove this inline comment?

2022-11-28 13:38 UTC, Morerice approved these changes

2022-11-28 15:00 UTC, RokPopov approved these changes

2022-11-29 07:46 UTC, merged