[PW-8047] Refactor RECURRING_CONTRACT webhook notification
Adyen/adyen-magento2 pull request #1957
Opened 2023-02-14 12:41 UTC by candemiralp

**Description**

After moving all of the tokenization functionality to Magento Vault, `RECURRING_CONTRACT` webhook handler needs to be refactored.

Removed all of the billing agreement functionality from the webhook handler. After obtaining the recurring payment reference from the synchronous `/payments` call, the plugin assumes everything works as expected unless it gets a failed (success=false) `RECURRING_CONTRACT` webhook notification. If a failing webhook arrives, the handler disables the payment token in `vault_payment_tokens` table.

**Tested scenarios**

- Successful / failed RECURRING_CONTRACT webhook processing

2023-02-15 08:58 UTC, Morerice requested changes

2023-02-15 08:58 UTC, Morerice commented on Helper/Webhook/RecurringContractWebhookHandler.php
> +                    "Vault payment token disabled due to the failing %s webhook notification.",
```suggestion
                    "Vault payment token with entity_id: %s disabled due to the failing %s webhook notification.",
```

2023-02-17 13:55 UTC, Morerice approved these changes

2023-02-20 08:27 UTC, RokPopov approved these changes

2023-02-20 09:28 UTC, merged