[PW-7707] - Remove 3DS2 model header while loading.
Adyen/adyen-magento2 pull request #1973
Opened 2023-02-24 15:03 UTC by raoulritter

**Description**

Fixes the pop up by not displaying the header model.

**Tested scenarios**

3DS Successful payment
3DS Failed

Fixes  
#1900

2023-02-27 13:12 UTC, Morerice requested changes

2023-02-27 13:12 UTC, Morerice commented on view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
> +                console.log(stateData);
```suggestion
```

2023-02-27 13:12 UTC, Morerice commented on view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js
> +                debugger;
```suggestion
```

2023-02-28 10:21 UTC, candemiralp approved these changes

2023-02-28 14:15 UTC, peterojo approved these changes

2023-02-28 14:30 UTC, merged