[PW-8225] Enable PBL for Admin api and document it
Adyen/adyen-magento2 pull request #2103
Opened 2023-07-04 13:54 UTC by RokPopov

**Description**
This PR makes PBL accessible for admin api. This involves updating the can_use_checkout flag for `adyen_pay_by_link` to 1, which results in `adyen_pay_by_link` payment method being returned in the `/payment-methods` call. However, since no entry is added in the `adyen-methods.js` file, PayByLink is still not shown in the frontend.

**Tested scenarios**
- make a /payment-methods call with REST and make sure that PBL is returned in the response
- make sure that on the checkout page of the storefront, PBL is not visible as a payment option
- make sure that you can make a payment using PBL via admin orders

2023-07-07 09:01 UTC, peterojo submitted a review, later dismissed

2023-07-11 12:14 UTC, peterojo approved these changes

2023-08-21 12:36 UTC, raoulritter approved these changes

2023-08-21 13:54 UTC, khushboo-singhvi approved these changes

2023-08-23 14:33 UTC, candemiralp requested changes

2023-08-23 14:33 UTC, candemiralp commented on etc/config.xml
> +        <can_use_checkout>1</can_use_checkout>
Did you check the response of Magento's internal payment-methods call? Pay-by-link shouldn't be in the available payment methods list for headless payments.

2023-09-07 07:45 UTC, candemiralp approved these changes

2024-04-16 11:42 UTC, closed without merging