[ECP-8625] Fix Apple Pay download certificate button URL
Adyen/adyen-magento2 pull request #2243
Opened 2023-09-27 08:31 UTC by khushboo-singhvi

**Description**
Apple Pay certificate download button now redirects to an existing URL. URL is being fetched from the code base, instead of getting it from the patch

**Tested scenarios**

Fixes

2023-09-27 12:27 UTC, peterojo approved these changes

2023-09-27 12:51 UTC, candemiralp requested changes

2023-09-27 12:51 UTC, candemiralp commented on Setup/Patch/Data/ApplePayCertificateUrlPath.php
This file needs to be removed. Config table is not being used anymore to fetch the URL.

2023-10-02 12:08 UTC, candemiralp approved these changes

2023-10-06 08:10 UTC, merged