Handling Refund Delay and Order Cancellation Issues when using Giftcard + redirected Payment method
Adyen/adyen-magento2 pull request #2771
Opened 2024-10-15 14:39 UTC by khushboo-singhvi

**Description**
When a customer places an order using a gift card in combination with any redirected payment method, an order is created which redeems the gift card balance, even if the full payment is not completed. As a result, the customer is unable to use the gift card again, despite the full order is not successfully placed.
This PR handles this situation wherein we cancel the already authorised partial payments(Giftcard Payments) if the payment with the redirect payment method fails.

**Tested scenarios**
Klarna, 3DS, Ideal Successful and failing situations tested.

Fixes

2024-10-23 11:45 UTC, candemiralp commented on Helper/PaymentResponseHandler.php
> +                }
What would you think about moving this logic to a separate private method? Currently, it decreases the readability and increases the overall complexity of the switch block.

2024-10-23 11:49 UTC, candemiralp commented on Helper/PaymentResponseHandler.php
> +                            $cancelResponse = $service->cancelOrder(new CancelOrderRequest($cancelRequest));
Could you please log the request and response of `/orders/cancel` endpoint ([example](https://github.com/Adyen/adyen-magento2/blob/b5309b0c0ac0aff9755c82ee23a2e0e88dde5ce7/Gateway/Http/Client/TransactionPayment.php#L149))?

2024-10-23 11:56 UTC, candemiralp commented on Helper/PaymentResponseHandler.php
> +                                return false;
Returning `false` here will terminate the execution of the rest of the method where we cancel the Magento order. In addition, checking the validity of a single field of an API response is not scalable.

Alternatively, you can catch the exception thrown from the PHP API Library and log the error message only. For responseCode 200, there is only one available value in the [API Explorer](https://docs.adyen.com/api-explorer/Checkout/71/post/orders/cancel#responses-200) which is `resultCode: Received`. So, if there is no exception thrown from the library, we can assume everything is good.

2024-10-28 11:09 UTC, peterojo commented on .github/workflows/main.yml
> +          tools: composer:2
```suggestion
          tools: composer:v2
```

2024-10-28 11:12 UTC, peterojo commented on Test/Unit/Helper/PaymentResponseHandlerTest.php
> +                        "pspReference":"ABC123","resultCode":"Authorised"}'
```suggestion
                        "pspReference":"ABC123",
                        "resultCode":"Authorised"
                      }'
```

2024-10-28 11:22 UTC, peterojo commented on Helper/PaymentResponseHandler.php
> +    private function hasActiveGiftCardPayments($merchantReference, $order)
This method not only checks if the payment "has active giftcard payments" but it also initializes the API client and attempts to cancel the order.
For proper separation of concerns, I would recommend implementing separate methods to check for used giftcards, and to make cancel calls (preferably using and reusable helper method used elsewhere)

2024-10-28 11:23 UTC, peterojo requested changes
A few changes requested

2024-11-05 14:12 UTC, candemiralp submitted a review, later dismissed

2024-11-06 10:35 UTC, peterojo commented on Helper/PaymentResponseHandler.php
> +use Adyen\Payment\Helper\Config as Config;
import name is reduntant here
```suggestion
use Adyen\Payment\Helper\Config;
```

2024-11-06 10:37 UTC, peterojo commented on Test/Unit/Helper/PaymentResponseHandlerTest.php
> +use Adyen\Payment\Helper\Config as Config;
Import alias is redundant
```suggestion
use Adyen\Payment\Helper\Config;
```

2024-11-06 11:42 UTC, candemiralp approved these changes

2024-11-11 11:08 UTC, SushmitaThakur approved these changes

2024-11-11 11:33 UTC, peterojo approved these changes

2024-11-12 08:39 UTC, merged