ApplePay and GooglePay -Terms & Conditions checkbox validation
Adyen/adyen-magento2 pull request #2809
Opened 2024-11-19 15:26 UTC by khushboo-singhvi

**Description**
Wallet payment methods such as ApplePay and GooglePay do not trigger the Terms and Conditions checkbox validation. When Terms and Conditions are enabled from Magento configuration, these wallet payment methods bypass the default form validation, as they mount their own "Place Order" buttons.
This PR solves the issue of Validating Terms & Conditions for ApplePay and GooglePay 

**Tested scenarios**

Fixes

2024-11-19 15:52 UTC, SushmitaThakur approved these changes

2024-11-20 11:36 UTC, peterojo approved these changes

2024-11-25 09:09 UTC, candemiralp requested changes

2024-11-25 09:09 UTC, candemiralp commented on view/frontend/web/js/view/payment/method-renderer/adyen-applepay-method.js
> +                googlePayConfiguration.onClick = function(resolve,reject) {
```suggestion
                applePayConfiguration.onClick = function(resolve, reject) {
```

2024-11-25 09:18 UTC, candemiralp approved these changes

2024-11-25 10:00 UTC, peterojo approved these changes

2024-11-25 10:31 UTC, merged