[PW-3708] Update the quoteid for refuse payments
Adyen/adyen-magento2 pull request #955
Opened 2021-01-21 15:08 UTC by AlexandrosMor

**Description**

Update the quoteid for refuse payments to avoid duplicated Quote IDs in sales_order_table

**Tested scenarios**

**Fixed issue**:  #915

2021-01-21 15:31 UTC, msilvagarcia submitted a review, later dismissed

2021-01-21 15:32 UTC, acampos1916 commented on Controller/Process/Result.php
> +                $currectQuote =  $session->getQuote();
```suggestion
                $currentQuote =  $session->getQuote();
```

2021-01-21 15:32 UTC, acampos1916 commented on Controller/Process/Result.php
> +                if (!empty($currectQuote)) {
```suggestion
                if (!empty($currentQuote)) {
```

2021-01-21 15:32 UTC, acampos1916 commented on Controller/Process/Result.php
> +                    $currentQuoteId = $currectQuote->getId();
```suggestion
                    $currentQuoteId = $currentQuote->getId();
```

2021-01-21 15:34 UTC, AlexandrosMor commented on Controller/Process/Result.php
> +                $currectQuote =  $session->getQuote();
ops :)

2021-01-21 15:36 UTC, peterojo approved these changes

2021-01-21 15:38 UTC, msilvagarcia requested changes

2021-01-21 15:38 UTC, msilvagarcia commented on Controller/Process/Result.php
> +                    $currectQuote->setIsActive(false);
```suggestion
                    $currentQuote->setIsActive(false);
```

2021-01-21 15:38 UTC, msilvagarcia commented on Controller/Process/Result.php
> +                    $newQuote->merge($currectQuote);
```suggestion
                    $newQuote->merge($currentQuote);
```

2021-01-21 15:38 UTC, msilvagarcia commented on Controller/Process/Result.php
> +                    $this->cartRepository->save($currectQuote);
```suggestion
                    $this->cartRepository->save($currentQuote);
```

2021-01-21 15:58 UTC, acampos1916 approved these changes

2021-01-21 16:07 UTC, peterojo approved these changes

2021-01-22 09:09 UTC, msilvagarcia approved these changes

2021-01-22 09:10 UTC, merged